version: '3.8'

services:
  authservice:
    build:
      context: ./Services/AuthService
    ports:
      - "5001:80"
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=authdb.db
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - authdb:/app

  flightservice:
    build:
      context: ./Services/FlightService
    ports:
      - "5002:80"
    environment:
      - MongoDbSettings__ConnectionString=mongodb://mongo:27017
      - MongoDbSettings__DatabaseName=FlightDb
    depends_on:
      - mongo

  bookingservice:
    build:
      context: ./Services/BookingService
    ports:
      - "5003:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqldata;Database=BookingDb;User=sa;Password=Your_password123;
    depends_on:
      - sqldata

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  authdb:
  mongodata:
  sqlserverdata:
