version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrongPassword123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  authservice:
    build:
      context: ./Services/AuthService
    ports:
      - "5001:5000"
    depends_on:
      - sqlserver

  flightservice:
    build:
      context: ./Services/FlightService
    ports:
      - "5002:5000"
    depends_on:
      - mongodb

  bookingservice:
    build:
      context: ./Services/BookingService
    ports:
      - "5003:5000"
    depends_on:
      - sqlserver
      - flightservice